version: 2.1
executors:
  node:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
    environment:
      NODE_ENV: development

commands:
  setup:
    steps:
      - checkout
      - run: yarn
jobs:
  build:
    executor:
      name: node
    
    steps:
      - setup
      - run: yarn lint
      - run: yarn test:ci
      - run: bash <(curl -s https://codecov.io/bash)
