version: 2.1
executors:
  node:
    docker:
        - image: mcr.microsoft.com/playwright:next
    environment:
        NODE_ENV: development

commands:
  setup:
    steps:
      - run:
        name: Install
        command: yarn
        
jobs:
  build:
    executor: node
    
  steps:
    - setup
    
    - run:
      name: Lint
      command: yarn lint
     
    - run: yarn lint:lit
    
    - run:
      name: Test
      command: yarn test

workflows:
  build:
    jobs:
      - build
