name: Deploy

# on:
#   release:
#     types: [published]
#     branches:
#       - master

on: [push]

jobs:
  build-site:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install and build
        run: |
          yarn
          yarn build

      - name: build site
        run: yarn site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
