name: Run Eslint

on: [push]

jobs:
  run-linters:
    name: Run Eslint
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install dependencies
      - name: install nodejs dependencies
        run: npm install

      - name: lint
        run: npm run lint
